### ISSUE TITLE
domain is removed when starting url path with 2 slashes

### ISSUE THREAD

**Issue by NielsH** [monkeysuffrage/phpuri#1]
Hi there,

I've got an issue when parsing an URL that has a path that starts with 2 slashes.

`echo phpUri::parse('http://google.com')->join('//blaat/test3/test/2//g3//////////5../../././..///../');  `

Outputs:
`http://blaat/test3/test/2/g3/`

When I use 1 slash, 3, 4, etc - it does work:
`echo phpUri::parse('http://google.com')->join('///blaat/test3/test/2//g3//////////5../../././..///../');`
`echo phpUri::parse('http://google.com')->join('////blaat/test3/test/2//g3//////////5../../././..///../');`

Outputs:
`http://google.com/blaat/test3/test/2/g3/`

**Comment by tzi** [comment]
It's the correct behavior according to me too.
A lot of CDN call are made with leading '//':
`<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>`

This issue could probably be closed. 

Cheers,  
Thomas.

**Comment by Habichtsberg** [comment]
In fact that is no issue.
why should you use double-slashes within an path?

Cheers, Dominik
