### ISSUE TITLE
Make to_str public

### ISSUE THREAD

**Issue by mikegleasonjr** [monkeysuffrage/phpuri#12]
Please 👍

**Comment by monkeysuffrage** [comment]
Why? What are you trying to do?

**Comment by mikegleasonjr** [comment]
I am trying to get a string representation of a parsed URL.

I parse it, then I manually change the `$scheme` or something else.. then I want to get the string.

**Comment by monkeysuffrage** [comment]
Sorry, you're going to have to fork it if you need that.
