### ISSUE TITLE
Support "broken" URIs

### ISSUE THREAD

**Issue by jhard** [monkeysuffrage/phpuri#16]
Things like redirects to `http://example.com?abc=123` are out there in the wild. It ought to be `http://example.com/?abc=123` obviously, but the world ain't perfect.
The problem arises when you do `phpUri::parse('http://example.com?abc=def')->join('index.html')` which leads to `http://example.comindex.html`, but should be (and browsers do handle it correctly) `http://example.com/index.html`.

**Comment by monkeysuffrage** [comment]
Yes, that looks like a bug.

**Comment by jhard** [comment]
I was just looking into it and wanted to write tests & fix it... turns out it's fixed in the current version, the version on packagist is just out of date.
Maybe that one could be updated, but this issue is solved <3

**Comment by monkeysuffrage** [comment]
Hmm. I'm actually not an expert at packagist and I don't do much PHP these
days. If you have a recommendation how to solve this I'd like to hear it.

**Comment by jhard** [comment]
Sadly, I'm even less of an expert regarding packagist.
Reading https://packagist.org/about, "How to update packages?", it should integrate somewhat seemlessly with github. However, I've never done that.
