### ISSUE TITLE
rel2abs beats phpUri on dot-segments

### ISSUE THREAD

**Issue by polomoshnov** [monkeysuffrage/phpuri#6]
echo rel2abs('../../../../test.php', 'http://example.com/a/b/c/d/f/g/test.php');
//==> http://example.com/a/b/test.php

echo phpUri::parse('http://example.com/a/b/c/d/f/g/test.php')->join('../../../../test.php');
//==> http://example.com/a/b/c/d/test.php

**Comment by Habichtsberg** [comment]
- open phpuri.php
- go to function "Normalize_path"
- look for the last preg_replace and change the -1 to 1 (the $limit).

Cheers,

Dominik

**Comment by monkeysuffrage** [comment]
Thanks Dominik,
How do you feel about making a push request?
- P

**Comment by Habichtsberg** [comment]
I'm currently up to, but the tests fail for two of your samples and I'm looking into it.
failure: http://g/ instead of http://g => rel: //g
failure: http://a/#s instead of http://a/b/c/d;p?q#s => rel: #s
phpuri:          successes -> 33, failures => 2, elapsed time: 0.001501

Cheers, Dominik

**Comment by Habichtsberg** [comment]
This is fixed now

**Comment by monkeysuffrage** [comment]
Ok, send another pull request if you need to and I will merge it.

**Comment by Habichtsberg** [comment]
There is a second pull-request #8 open which needs to be merged.

Cheers, Dominik

**Comment by Habichtsberg** [comment]
This bug-report may be closed now.
